import type { PracticeCatalogItem } from "../../types/practice";

export const practiceCatalog: PracticeCatalogItem[] = [
  {
    slug: "revisao",
    title: "Revisão",
    shortTitle: "Revisão",
    summary: "Mapa inicial do curso com conceitos-chave, organização do semestre e preparação para as práticas subsequentes.",
    status: "available",
    hasSimulator: false,
    simulatorSummary: "Sem simulador definido para esta etapa",
    materialStatus: "Roteiro reestruturado com base no PDF da prática 1",
    sourceStatus: "PDF base incorporado",
    availableMaterials: ["roteiro em desenvolvimento", "estrutura da prática"],
    plannedMaterials: ["simuladores externos, se aplicável"],
    pdfDownloadPath: "/downloads/praticas/revisao.pdf",
    pdfTrackingResourceSlug: "principal",
  },
  {
    slug: "carga-massa",
    title: "Carga-massa",
    shortTitle: "Carga-massa",
    summary: "Prática dedicada à razão carga-massa, com roteiro experimental, aquisição de dados e leitura física dos resultados.",
    status: "available",
    hasSimulator: false,
    simulatorSummary: "Simulador ainda não selecionado",
    materialStatus: "Página estrutural pronta para receber o PDF da prática",
    sourceStatus: "Aguardando PDF e materiais de apoio",
    availableMaterials: ["roteiro em desenvolvimento", "estrutura da prática"],
    plannedMaterials: ["simulador interno ou externo, se aprovado"],
    pdfDownloadPath: "/downloads/praticas/carga-massa.pdf",
    pdfTrackingResourceSlug: "principal",
  },
  {
    slug: "radiacao-termica",
    title: "Radiação térmica",
    shortTitle: "Radiação térmica",
    summary: "Estudo experimental da emissão, transmissão e reflexão de radiação térmica com cubo de Leslie e sensor termopar.",
    status: "available",
    hasSimulator: true,
    simulatorSummary: "Simulador externo para espectro de corpo negro e efeito da temperatura",
    materialStatus: "Roteiro reestruturado e pronto para uso em aula",
    sourceStatus: "Apostila da disciplina, folhas de laboratório e bibliografia introdutória",
    availableMaterials: ["roteiro completo", "tabelas de aquisição", "orientação de relatório", "simulador externo"],
    plannedMaterials: ["ajustes finos após uso em aula"],
    pdfDownloadPath: "/downloads/praticas/radiacao-termica.pdf",
  },
  {
    slug: "stefan-boltzmann",
    title: "Stefan-Boltzmann",
    shortTitle: "Stefan-Boltzmann",
    summary: "Exploração experimental da lei de Stefan-Boltzmann e da relação entre potência radiada e temperatura.",
    status: "available",
    hasSimulator: true,
    simulatorSummary: "Simulador externo para espectro de corpo negro e dependência com a temperatura",
    materialStatus: "Roteiro reestruturado e pronto para uso em aula",
    sourceStatus: "Material da disciplina, folha de manipulação, planilha de ajuste e bibliografia introdutória",
    availableMaterials: ["roteiro completo", "tabelas de aquisição", "orientação de relatório", "simulador externo"],
    plannedMaterials: ["ajustes finos após uso em aula"],
    pdfDownloadPath: "/downloads/praticas/stefan-boltzmann.pdf",
    pdfTrackingResourceSlug: "principal",
  },
  {
    slug: "efeito-fotoeletrico",
    title: "Efeito fotoelétrico",
    shortTitle: "Efeito fotoelétrico",
    summary: "Prática sobre emissão fotoelétrica, potencial de corte e interpretação em termos quânticos.",
    status: "available",
    hasSimulator: true,
    simulatorSummary: "Roteiro guiado e simulador interativo para explorar tensão de corte e frequência",
    materialStatus: "Roteiro reestruturado e pronto para uso em aula",
    sourceStatus: "Apostila da disciplina, folha de laboratório, manual PASCO e bibliografia introdutória",
    availableMaterials: ["roteiro completo", "tabelas de aquisição", "orientação de relatório", "simuladores externos"],
    plannedMaterials: ["ajustes finos após uso em aula"],
    pdfDownloadPath: "/downloads/praticas/efeito-fotoeletrico.pdf",
    pdfTrackingResourceSlug: "principal",
  },
  {
    slug: "espectroscopia",
    title: "Linhas espectrais",
    shortTitle: "Linhas espectrais",
    summary: "Determinação experimental da constante de Rydberg a partir das linhas visíveis da série de Balmer do hidrogênio.",
    status: "available",
    hasSimulator: true,
    simulatorSummary: "Simulador de espectro de emissão do hidrogênio para análise separada das linhas de Balmer",
    materialStatus: "Roteiro reestruturado e pronto para revisão em aula",
    sourceStatus: "Apostila da disciplina, folhas de laboratório e roteiro do simulador",
    availableMaterials: ["roteiro completo", "tabelas de aquisição", "orientação de relatório", "simulador externo"],
    plannedMaterials: ["PDF final após a revisão do conteúdo"],
  },
  {
    slug: "difracao",
    title: "Difração de elétrons",
    shortTitle: "Difração",
    summary: "Verificação do comportamento ondulatório dos elétrons e determinação dos espaçamentos interplanares do grafite.",
    status: "available",
    hasSimulator: true,
    simulatorSummary: "Simulador da UFC com ajuste da alta tensão e medida dos diâmetros dos anéis",
    materialStatus: "Roteiro reestruturado e pronto para revisão em aula",
    sourceStatus: "Apostila e folhas do Laboratório 7, figuras fornecidas e simulador da UFC",
    availableMaterials: ["roteiro completo", "tabelas de aquisição", "orientação de relatório", "simulador externo"],
    plannedMaterials: ["PDF final após a revisão do conteúdo"],
  },
  {
    slug: "diodos",
    title: "Diodos",
    shortTitle: "Diodos",
    summary: "Caracterização de diodos, curvas de resposta e discussão de comportamento em diferentes regimes.",
    status: "planned",
    hasSimulator: false,
    simulatorSummary: "Nenhum simulador definido por enquanto",
    materialStatus: "Catálogo criado; conteúdo ainda não iniciado",
    sourceStatus: "Aguardando PDF antigo",
    availableMaterials: [],
    plannedMaterials: ["pdf antigo", "suporte teórico"],
  },
  {
    slug: "radioatividade",
    title: "Radioatividade",
    shortTitle: "Radioatividade",
    summary: "Estudo experimental de contagens, decaimento e interpretação estatística de medidas radioativas.",
    status: "planned",
    hasSimulator: true,
    simulatorSummary: "Simulador previsto, ainda a definir",
    materialStatus: "Catálogo criado; conteúdo ainda não iniciado",
    sourceStatus: "Aguardando PDF antigo",
    availableMaterials: [],
    plannedMaterials: ["pdf antigo", "simulador a definir"],
  },
];

export const enabledPracticeSlugs = practiceCatalog
  .filter((practice) => practice.status === "available")
  .map((practice) => practice.slug);

export const practiceCounts = {
  total: practiceCatalog.length,
  available: practiceCatalog.filter((practice) => practice.status === "available").length,
  planned: practiceCatalog.filter((practice) => practice.status === "planned").length,
  withSimulators: practiceCatalog.filter((practice) => practice.hasSimulator).length,
};

export const availablePractices = practiceCatalog.filter((practice) => practice.status === "available");
export const plannedPractices = practiceCatalog.filter((practice) => practice.status === "planned");

export function getPracticeCatalogItem(slug: string) {
  return practiceCatalog.find((practice) => practice.slug === slug);
}
